[workspace]

[package]
name = "tools"
edition = "2021"

[[bin]]
name = "tools"
path = "./tools.rs"

[dependencies]
espflash = { git = "https://github.com/rustbox/espflash", rev = "5c00054bdc2cb4fa07c8e6216d8aca3949825079", artifact = "bin" }
