[package]
name = "tap"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tap"
path = "main.rs"

[dependencies]
tun-tap = { version = "0.1.4", default-features = false, features = [] }
pkt = { path = "../pkt" }
